#!/bin/sh
VNAME="killswitch v1"
VINFO="Enigma2 / Wireguard killswitch by LouCipher & muplagama"
case "$1" in
    start)
        check_run=$(pgrep killswitch.sh)
        if  [ -n "$check_run" ]
        then
        echo "killwitch already running"
        else
        echo "starting killswitch"
        /etc/wireguard/killswitch.sh&
        fi
        ;;
     stop)
        check_stop=$(pgrep killswitch.sh)
        if  [ -n "$check_stop" ]
        then
        echo "terminating killswitch"
        pkill killswitch.sh
        else
        echo "killswitch already down"
        fi
        ;;
     restart)
        pkill killswitch.sh
        /etc/wireguard/killswitch.sh&
        ;;
     status)
        check_ps=$(pgrep killswitch.sh)
        if  [ -n  "$check_ps" ]
        then
        echo "killswitch is running"
        else
        echo "killswitch is NOT running"
        fi
        ;;
     version)
        echo "$VNAME"
        ;;
     info)
        echo "$VINFO"
        ;;
    *)
        echo "usage: $0 start|stop|restart|status|version|info" >&2
       exit 1
       ;;
esac
exit 0
