#!/bin/sh
WGDIR=/etc/wireguard
NAME=killswitch
RC=/etc/init.d/$NAME
VNAME="killswitch v2"
VINFO="Enigma2 / Wireguard killswitch by LouCipher & muplagama"

case "$1" in
    start)
        check_run=$(pgrep $NAME.sh)
        if  [ -n "$check_run" ]
        then
        echo "$NAME already running"
        else
        echo "starting $NAME"
        $WGDIR/$NAME.sh&
        fi
        ;;
     stop)
        check_stop=$(pgrep $NAME.sh)
        if  [ -n "$check_stop" ]
        then
        echo "terminating $NAME"
        pkill $NAME.sh
        else
        echo "$NAME already down"
        fi
        ;;
     restart)
        pkill $NAME.sh
        $WGDIR/$NAME.sh&
        ;;
     status)
        check_ps=$(pgrep $NAME.sh)
        if  [ -n  "$check_ps" ]
        then
        echo "$NAME is running"
        else
        echo "$NAME is NOT running"
        fi
        ;;
     enable)
        echo "enable autostart"
        update-rc.d $NAME defaults > /dev/null 2>&1
        $RC start
        $RC status
        ;;
     disable)
        $RC stop
        echo "remove autostart"
        update-rc.d -f $NAME remove > /dev/null 2>&1
        $RC status
        ;;
     uninstall)
	echo "remove autostart"
	$RC disable
	echo "remove files"
	rm $WGDIR/$NAME
	rm $RC
	echo "..done"
	;;
     version)
        echo "$VNAME"
        ;;
     info)
        echo "$VINFO"
        ;;
    *)
        echo "usage: $0 start|stop|restart|status|enable|disable|uninstall|version|info" >&2
       exit 1
       ;;
esac
exit 0
